import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { Octokit } from "@octokit/rest";
import { getRequiredEnv } from "./config/env.js";
import { registerGithubCheckDependabotSecurityUpdatesTool } from "./tools/repositories/github-check-dependabot-security-updates.js";
import { registerGithubCheckPrivateVulnerabilityReportingTool } from "./tools/repositories/github-check-private-vulnerability-reporting.js";
import { registerGithubCheckImmutableReleasesTool } from "./tools/repositories/github-check-immutable-releases.js";
import { registerGithubCheckVulnerabilityAlertsTool } from "./tools/repositories/github-check-vulnerability-alerts.js";
import { registerGithubEnableImmutableReleasesTool } from "./tools/repositories/github-enable-immutable-releases.js";
import { registerGithubDisableImmutableReleasesTool } from "./tools/repositories/github-disable-immutable-releases.js";
import { registerGithubDisableDependabotSecurityUpdatesTool } from "./tools/repositories/github-disable-dependabot-security-updates.js";
import { registerGithubEnableDependabotSecurityUpdatesTool } from "./tools/repositories/github-enable-dependabot-security-updates.js";
import { registerGithubDisablePrivateVulnerabilityReportingTool } from "./tools/repositories/github-disable-private-vulnerability-reporting.js";
import { registerGithubEnablePrivateVulnerabilityReportingTool } from "./tools/repositories/github-enable-private-vulnerability-reporting.js";
import { registerGithubDisableVulnerabilityAlertsTool } from "./tools/repositories/github-disable-vulnerability-alerts.js";
import { registerGithubEnableVulnerabilityAlertsTool } from "./tools/repositories/github-enable-vulnerability-alerts.js";
import { registerGithubCreateOrgRepoTool } from "./tools/repositories/github-create-org-repo.js";
import { registerGithubCreatePersonalRepoTool } from "./tools/repositories/github-create-personal-repo.js";
import { registerGithubCreateRepoFromTemplateTool } from "./tools/repositories/github-create-repo-from-template.js";
import { registerGithubCreateRepoAttestationTool } from "./tools/repositories/attestations/github-create-repo-attestation.js";
import { registerGithubListRepoAttestationsTool } from "./tools/repositories/attestations/github-list-repo-attestations.js";
import { registerGithubCreateRepoAutolinkTool } from "./tools/repositories/autolinks/github-create-repo-autolink.js";
import { registerGithubDeleteRepoAutolinkTool } from "./tools/repositories/autolinks/github-delete-repo-autolink.js";
import { registerGithubGetRepoAutolinkTool } from "./tools/repositories/autolinks/github-get-repo-autolink.js";
import { registerGithubListRepoAutolinksTool } from "./tools/repositories/autolinks/github-list-repo-autolinks.js";
import { registerGithubCreateUpdateRepoCustomPropertyValuesTool } from "./tools/repositories/custom-properties/github-create-update-repo-custom-property-values.js";
import { registerGithubGetRepoCustomPropertyValuesTool } from "./tools/repositories/custom-properties/github-get-repo-custom-property-values.js";
import { registerGithubCreateRepoDispatchTool } from "./tools/repositories/github-create-repo-dispatch.js";
import { registerGithubDeleteRepoTool } from "./tools/repositories/github-delete-repo.js";
import { registerGithubGetRepoTool } from "./tools/repositories/github-get-repo.js";
import { registerGithubCreateUpdateFileContentsTool } from "./tools/repositories/contents/github-create-update-file-contents.js";
import { registerGithubDeleteFileTool } from "./tools/repositories/contents/github-delete-file.js";
import { registerGithubDownloadRepoArchiveTarTool } from "./tools/repositories/contents/github-download-repo-archive-tar.js";
import { registerGithubDownloadRepoArchiveZipTool } from "./tools/repositories/contents/github-download-repo-archive-zip.js";
import { registerGithubGetRepoContentTool } from "./tools/repositories/contents/github-get-repo-content.js";
import { registerGithubGetRepoReadmeTool } from "./tools/repositories/contents/github-get-repo-readme.js";
import { registerGithubGetRepoReadmeInDirectoryTool } from "./tools/repositories/contents/github-get-repo-readme-in-directory.js";
import { registerGithubListCodeownersErrorsTool } from "./tools/repositories/github-list-codeowners-errors.js";
import { registerGithubListRepoContributorsTool } from "./tools/repositories/github-list-repo-contributors.js";
import { registerGithubListRepoActivitiesTool } from "./tools/repositories/github-list-repo-activities.js";
import { registerGithubListAuthenticatedUserReposTool } from "./tools/repositories/github-list-authenticated-user-repos.js";
import { registerGithubDeleteOrgTool } from "./tools/organizations/github-delete-org.js";
import { registerGithubGetOrgRouteStatsByActorTool } from "./tools/organizations/api-insights/github-get-org-route-stats-by-actor.js";
import { registerGithubGetOrgSubjectStatsTool } from "./tools/organizations/api-insights/github-get-org-subject-stats.js";
import { registerGithubGetOrgSummaryStatsTool } from "./tools/organizations/api-insights/github-get-org-summary-stats.js";
import { registerGithubGetOrgSummaryStatsByActorTool } from "./tools/organizations/api-insights/github-get-org-summary-stats-by-actor.js";
import { registerGithubGetOrgSummaryStatsByUserTool } from "./tools/organizations/api-insights/github-get-org-summary-stats-by-user.js";
import { registerGithubGetOrgTimeStatsTool } from "./tools/organizations/api-insights/github-get-org-time-stats.js";
import { registerGithubGetOrgTimeStatsByActorTool } from "./tools/organizations/api-insights/github-get-org-time-stats-by-actor.js";
import { registerGithubGetOrgTimeStatsByUserTool } from "./tools/organizations/api-insights/github-get-org-time-stats-by-user.js";
import { registerGithubGetOrgUserStatsTool } from "./tools/organizations/api-insights/github-get-org-user-stats.js";
import { registerGithubCreateUpdateOrgCustomPropertiesTool } from "./tools/organizations/custom-properties/github-create-update-org-custom-properties.js";
import { registerGithubCreateUpdateOrgCustomPropertyTool } from "./tools/organizations/custom-properties/github-create-update-org-custom-property.js";
import { registerGithubCreateUpdateOrgCustomPropertyValuesTool } from "./tools/organizations/custom-properties/github-create-update-org-custom-property-values.js";
import { registerGithubDeleteOrgCustomPropertyTool } from "./tools/organizations/custom-properties/github-delete-org-custom-property.js";
import { registerGithubGetOrgCustomPropertyTool } from "./tools/organizations/custom-properties/github-get-org-custom-property.js";
import { registerGithubListOrgCustomPropertyValuesTool } from "./tools/organizations/custom-properties/github-list-org-custom-property-values.js";
import { registerGithubGetOrgCustomPropertiesTool } from "./tools/organizations/custom-properties/github-get-org-custom-properties.js";
import { registerGithubCreateOrgIssueFieldTool } from "./tools/organizations/issue-fields/github-create-org-issue-field.js";
import { registerGithubDeleteOrgIssueFieldTool } from "./tools/organizations/issue-fields/github-delete-org-issue-field.js";
import { registerGithubListOrgIssueFieldsTool } from "./tools/organizations/issue-fields/github-list-org-issue-fields.js";
import { registerGithubUpdateOrgIssueFieldTool } from "./tools/organizations/issue-fields/github-update-org-issue-field.js";
import { registerGithubCreateOrgIssueTypeTool } from "./tools/organizations/issue-types/github-create-org-issue-type.js";
import { registerGithubDeleteOrgIssueTypeTool } from "./tools/organizations/issue-types/github-delete-org-issue-type.js";
import { registerGithubListOrgIssueTypesTool } from "./tools/organizations/issue-types/github-list-org-issue-types.js";
import { registerGithubUpdateOrgIssueTypeTool } from "./tools/organizations/issue-types/github-update-org-issue-type.js";
import { registerGithubGetOrgTool } from "./tools/organizations/github-get-org.js";
import { registerGithubGetOrgImmutableReleasesSettingsTool } from "./tools/organizations/github-get-org-immutable-releases-settings.js";
import { registerGithubDisableImmutableReleasesForOrgRepoTool } from "./tools/organizations/github-disable-immutable-releases-for-org-repo.js";
import { registerGithubEnableImmutableReleasesForOrgRepoTool } from "./tools/organizations/github-enable-immutable-releases-for-org-repo.js";
import { registerGithubCreateOrgArtifactDeploymentRecordTool } from "./tools/organizations/artifact-metadata/github-create-org-artifact-deployment-record.js";
import { registerGithubCreateOrgMetadataStorageRecordTool } from "./tools/organizations/artifact-metadata/github-create-org-metadata-storage-record.js";
import { registerGithubListOrgArtifactDeploymentRecordsTool } from "./tools/organizations/artifact-metadata/github-list-org-artifact-deployment-records.js";
import { registerGithubListOrgMetadataStorageRecordsTool } from "./tools/organizations/artifact-metadata/github-list-org-metadata-storage-records.js";
import { registerGithubDeleteOrgAttestationByIdTool } from "./tools/organizations/artifact-attestations/github-delete-org-attestation-by-id.js";
import { registerGithubDeleteOrgAttestationBySubjectDigestTool } from "./tools/organizations/artifact-attestations/github-delete-org-attestation-by-subject-digest.js";
import { registerGithubDeleteOrgAttestationsBulkTool } from "./tools/organizations/artifact-attestations/github-delete-org-attestations-bulk.js";
import { registerGithubListOrgAttestationReposTool } from "./tools/organizations/artifact-attestations/github-list-org-attestation-repos.js";
import { registerGithubListOrgAttestationsTool } from "./tools/organizations/artifact-attestations/github-list-org-attestations.js";
import { registerGithubListOrgAttestationsBulkSubjectDigestsTool } from "./tools/organizations/artifact-attestations/github-list-org-attestations-bulk-subject-digests.js";
import { registerGithubBlockOrgUserTool } from "./tools/organizations/blocking-users/github-block-org-user.js";
import { registerGithubCheckOrgBlockedUserTool } from "./tools/organizations/blocking-users/github-check-org-blocked-user.js";
import { registerGithubListOrgBlockedUsersTool } from "./tools/organizations/blocking-users/github-list-org-blocked-users.js";
import { registerGithubUnblockOrgUserTool } from "./tools/organizations/blocking-users/github-unblock-org-user.js";
import { registerGithubCancelOrgInvitationTool } from "./tools/organizations/members/github-cancel-org-invitation.js";
import { registerGithubCheckOrgMembershipForUserTool } from "./tools/organizations/members/github-check-org-membership-for-user.js";
import { registerGithubCheckOrgPublicMembershipForUserTool } from "./tools/organizations/members/github-check-org-public-membership-for-user.js";
import { registerGithubSetPublicOrgMembershipForAuthUserTool } from "./tools/organizations/members/github-set-public-org-membership-for-auth-user.js";
import { registerGithubRemovePublicOrgMembershipForAuthUserTool } from "./tools/organizations/members/github-remove-public-org-membership-for-auth-user.js";
import { registerGithubCreateOrgInvitationTool } from "./tools/organizations/members/github-create-org-invitation.js";
import { registerGithubGetOrgMembershipForUserTool } from "./tools/organizations/members/github-get-org-membership-for-user.js";
import { registerGithubSetOrgMembershipForUserTool } from "./tools/organizations/members/github-set-org-membership-for-user.js";
import { registerGithubListOrgFailedInvitationsTool } from "./tools/organizations/members/github-list-org-failed-invitations.js";
import { registerGithubListOrgInvitationTeamsTool } from "./tools/organizations/members/github-list-org-invitation-teams.js";
import { registerGithubListOrgMembersTool } from "./tools/organizations/members/github-list-org-members.js";
import { registerGithubListOrgPublicMembersTool } from "./tools/organizations/members/github-list-org-public-members.js";
import { registerGithubListOrgPendingInvitationsTool } from "./tools/organizations/members/github-list-org-pending-invitations.js";
import { registerGithubRemoveOrgMemberTool } from "./tools/organizations/members/github-remove-org-member.js";
import { registerGithubRemoveOrgMembershipForUserTool } from "./tools/organizations/members/github-remove-org-membership-for-user.js";
import { registerGithubSetOrgClusterDeploymentRecordsTool } from "./tools/organizations/artifact-metadata/github-set-org-cluster-deployment-records.js";
import { registerGithubEnableOrDisableOrgSecurityFeatureTool } from "./tools/organizations/github-enable-or-disable-org-security-feature.js";
import { registerGithubListImmutableReleasesForOrgReposTool } from "./tools/organizations/github-list-immutable-releases-for-org-repos.js";
import { registerGithubListOrgAppInstallationsTool } from "./tools/organizations/github-list-org-app-installations.js";
import { registerGithubDeleteOrgNetworkConfigurationTool } from "./tools/organizations/network-configurations/github-delete-org-network-configuration.js";
import { registerGithubCreateOrgNetworkConfigurationTool } from "./tools/organizations/network-configurations/github-create-org-network-configuration.js";
import { registerGithubGetOrgNetworkConfigurationTool } from "./tools/organizations/network-configurations/github-get-org-network-configuration.js";
import { registerGithubGetOrgNetworkSettingsTool } from "./tools/organizations/network-configurations/github-get-org-network-settings.js";
import { registerGithubListOrgNetworkConfigurationsTool } from "./tools/organizations/network-configurations/github-list-org-network-configurations.js";
import { registerGithubListOrgRolesTool } from "./tools/organizations/organization-roles/github-list-org-roles.js";
import { registerGithubRemoveAllOrgRolesForTeamTool } from "./tools/organizations/organization-roles/github-remove-all-org-roles-for-team.js";
import { registerGithubAssignOrgRoleToTeamTool } from "./tools/organizations/organization-roles/github-assign-org-role-to-team.js";
import { registerGithubRemoveOrgRoleFromTeamTool } from "./tools/organizations/organization-roles/github-remove-org-role-from-team.js";
import { registerGithubRemoveAllOrgRolesForUserTool } from "./tools/organizations/organization-roles/github-remove-all-org-roles-for-user.js";
import { registerGithubAssignOrgRoleToUserTool } from "./tools/organizations/organization-roles/github-assign-org-role-to-user.js";
import { registerGithubRemoveOrgRoleFromUserTool } from "./tools/organizations/organization-roles/github-remove-org-role-from-user.js";
import { registerGithubGetOrgRoleTool } from "./tools/organizations/organization-roles/github-get-org-role.js";
import { registerGithubListTeamsAssignedToOrgRoleTool } from "./tools/organizations/organization-roles/github-list-teams-assigned-to-org-role.js";
import { registerGithubListUsersAssignedToOrgRoleTool } from "./tools/organizations/organization-roles/github-list-users-assigned-to-org-role.js";
import { registerGithubListOrgOutsideCollaboratorsTool } from "./tools/organizations/outside-collaborators/github-list-org-outside-collaborators.js";
import { registerGithubConvertOrgMemberToOutsideCollaboratorTool } from "./tools/organizations/outside-collaborators/github-convert-org-member-to-outside-collaborator.js";
import { registerGithubRemoveOrgOutsideCollaboratorTool } from "./tools/organizations/outside-collaborators/github-remove-org-outside-collaborator.js";
import { registerGithubListOrgPatRequestsTool } from "./tools/organizations/personal-access-tokens/github-list-org-pat-requests.js";
import { registerGithubReviewOrgPatRequestsTool } from "./tools/organizations/personal-access-tokens/github-review-org-pat-requests.js";
import { registerGithubReviewOrgPatRequestTool } from "./tools/organizations/personal-access-tokens/github-review-org-pat-request.js";
import { registerGithubListOrgPatRequestRepositoriesTool } from "./tools/organizations/personal-access-tokens/github-list-org-pat-request-repositories.js";
import { registerGithubListOrgPatsTool } from "./tools/organizations/personal-access-tokens/github-list-org-pats.js";
import { registerGithubUpdateOrgPatsTool } from "./tools/organizations/personal-access-tokens/github-update-org-pats.js";
import { registerGithubUpdateOrgPatTool } from "./tools/organizations/personal-access-tokens/github-update-org-pat.js";
import { registerGithubListOrgPatRepositoriesTool } from "./tools/organizations/personal-access-tokens/github-list-org-pat-repositories.js";
import { registerGithubListOrgRuleSuitesTool } from "./tools/organizations/rule-suites/github-list-org-rule-suites.js";
import { registerGithubGetOrgRuleSuiteTool } from "./tools/organizations/rule-suites/github-get-org-rule-suite.js";
import { registerGithubListOrgRulesetsTool } from "./tools/organizations/rules/github-list-org-rulesets.js";
import { registerGithubCreateOrgRulesetTool } from "./tools/organizations/rules/github-create-org-ruleset.js";
import { registerGithubGetOrgRulesetTool } from "./tools/organizations/rules/github-get-org-ruleset.js";
import { registerGithubUpdateOrgRulesetTool } from "./tools/organizations/rules/github-update-org-ruleset.js";
import { registerGithubDeleteOrgRulesetTool } from "./tools/organizations/rules/github-delete-org-ruleset.js";
import { registerGithubGetOrgRulesetHistoryTool } from "./tools/organizations/rules/github-get-org-ruleset-history.js";
import { registerGithubGetOrgRulesetVersionTool } from "./tools/organizations/rules/github-get-org-ruleset-version.js";
import { registerGithubAddOrgSecurityManagerTeamTool } from "./tools/organizations/security-managers/github-add-org-security-manager-team.js";
import { registerGithubListOrgSecurityManagerTeamsTool } from "./tools/organizations/security-managers/github-list-org-security-manager-teams.js";
import { registerGithubRemoveOrgSecurityManagerTeamTool } from "./tools/organizations/security-managers/github-remove-org-security-manager-team.js";
import { registerGithubCreateOrgWebhookTool } from "./tools/organizations/webhooks/github-create-org-webhook.js";
import { registerGithubDeleteOrgWebhookTool } from "./tools/organizations/webhooks/github-delete-org-webhook.js";
import { registerGithubGetOrgWebhookDeliveryTool } from "./tools/organizations/webhooks/github-get-org-webhook-delivery.js";
import { registerGithubGetOrgWebhookConfigTool } from "./tools/organizations/webhooks/github-get-org-webhook-config.js";
import { registerGithubGetOrgWebhookTool } from "./tools/organizations/webhooks/github-get-org-webhook.js";
import { registerGithubListOrgWebhookDeliveriesTool } from "./tools/organizations/webhooks/github-list-org-webhook-deliveries.js";
import { registerGithubPingOrgWebhookTool } from "./tools/organizations/webhooks/github-ping-org-webhook.js";
import { registerGithubRedeliverOrgWebhookDeliveryTool } from "./tools/organizations/webhooks/github-redeliver-org-webhook-delivery.js";
import { registerGithubListOrgWebhooksTool } from "./tools/organizations/webhooks/github-list-org-webhooks.js";
import { registerGithubUpdateOrgWebhookConfigTool } from "./tools/organizations/webhooks/github-update-org-webhook-config.js";
import { registerGithubUpdateOrgWebhookTool } from "./tools/organizations/webhooks/github-update-org-webhook.js";
import { registerGithubUpdateOrgNetworkConfigurationTool } from "./tools/organizations/network-configurations/github-update-org-network-configuration.js";
import { registerGithubListOrganizationsTool } from "./tools/organizations/github-list-organizations.js";
import { registerGithubListOrgsForAuthenticatedUserTool } from "./tools/organizations/github-list-orgs-for-authenticated-user.js";
import { registerGithubGetOrgMembershipForAuthUserTool } from "./tools/organizations/github-get-org-membership-for-auth-user.js";
import { registerGithubUpdateOrgMembershipForAuthUserTool } from "./tools/organizations/github-update-org-membership-for-auth-user.js";
import { registerGithubListOrgMembershipsForAuthUserTool } from "./tools/organizations/github-list-org-memberships-for-auth-user.js";
import { registerGithubListOrgsForUserTool } from "./tools/organizations/github-list-orgs-for-user.js";
import { registerGithubSetImmutableReleasesForOrgReposTool } from "./tools/organizations/github-set-immutable-releases-for-org-repos.js";
import { registerGithubSetOrgImmutableReleasesSettingsTool } from "./tools/organizations/github-set-org-immutable-releases-settings.js";
import { registerGithubUpdateOrgTool } from "./tools/organizations/github-update-org.js";
import { registerGithubListOrgReposTool } from "./tools/repositories/github-list-org-repos.js";
import { registerGithubListPublicReposTool } from "./tools/repositories/github-list-public-repos.js";
import { registerGithubCreateRepoForkTool } from "./tools/repositories/forks/github-create-repo-fork.js";
import { registerGithubListRepoForksTool } from "./tools/repositories/forks/github-list-repo-forks.js";
import { registerGithubCreateRepoRulesetTool } from "./tools/repositories/rules/github-create-repo-ruleset.js";
import { registerGithubDeleteRepoRulesetTool } from "./tools/repositories/rules/github-delete-repo-ruleset.js";
import { registerGithubGetRepoBranchRulesTool } from "./tools/repositories/rules/github-get-repo-branch-rules.js";
import { registerGithubGetRepoRulesetTool } from "./tools/repositories/rules/github-get-repo-ruleset.js";
import { registerGithubGetRepoRulesetHistoryTool } from "./tools/repositories/rules/github-get-repo-ruleset-history.js";
import { registerGithubGetRepoRulesetVersionTool } from "./tools/repositories/rules/github-get-repo-ruleset-version.js";
import { registerGithubListRepoRulesetsTool } from "./tools/repositories/rules/github-list-repo-rulesets.js";
import { registerGithubUpdateRepoRulesetTool } from "./tools/repositories/rules/github-update-repo-ruleset.js";
import { registerGithubGetRepoRuleSuiteTool } from "./tools/repositories/rule-suites/github-get-repo-rule-suite.js";
import { registerGithubListRepoRuleSuitesTool } from "./tools/repositories/rule-suites/github-list-repo-rule-suites.js";
import { registerGithubListRepoLanguagesTool } from "./tools/repositories/github-list-repo-languages.js";
import { registerGithubListRepoTagsTool } from "./tools/repositories/github-list-repo-tags.js";
import { registerGithubListRepoTeamsTool } from "./tools/repositories/github-list-repo-teams.js";
import { registerGithubListRepoTopicsTool } from "./tools/repositories/github-list-repo-topics.js";
import { registerGithubListUserReposTool } from "./tools/repositories/github-list-user-repos.js";
import { registerGithubCreateRepoWebhookTool } from "./tools/repositories/webhooks/github-create-repo-webhook.js";
import { registerGithubDeleteRepoWebhookTool } from "./tools/repositories/webhooks/github-delete-repo-webhook.js";
import { registerGithubGetRepoWebhookConfigTool } from "./tools/repositories/webhooks/github-get-repo-webhook-config.js";
import { registerGithubGetRepoWebhookDeliveryTool } from "./tools/repositories/webhooks/github-get-repo-webhook-delivery.js";
import { registerGithubGetRepoWebhookTool } from "./tools/repositories/webhooks/github-get-repo-webhook.js";
import { registerGithubListRepoWebhookDeliveriesTool } from "./tools/repositories/webhooks/github-list-repo-webhook-deliveries.js";
import { registerGithubListRepoWebhooksTool } from "./tools/repositories/webhooks/github-list-repo-webhooks.js";
import { registerGithubPingRepoWebhookTool } from "./tools/repositories/webhooks/github-ping-repo-webhook.js";
import { registerGithubTestPushRepoWebhookTool } from "./tools/repositories/webhooks/github-test-push-repo-webhook.js";
import { registerGithubRedeliverRepoWebhookDeliveryTool } from "./tools/repositories/webhooks/github-redeliver-repo-webhook-delivery.js";
import { registerGithubUpdateRepoWebhookConfigTool } from "./tools/repositories/webhooks/github-update-repo-webhook-config.js";
import { registerGithubUpdateRepoWebhookTool } from "./tools/repositories/webhooks/github-update-repo-webhook.js";
import { registerGithubListArtifactsForRepoTool } from "./tools/actions/artifacts/github-list-artifacts-for-repo.js";
import { registerGithubGetArtifactTool } from "./tools/actions/artifacts/github-get-artifact.js";
import { registerGithubDeleteArtifactTool } from "./tools/actions/artifacts/github-delete-artifact.js";
import { registerGithubDownloadArtifactTool } from "./tools/actions/artifacts/github-download-artifact.js";
import { registerGithubListWorkflowRunArtifactsTool } from "./tools/actions/artifacts/github-list-workflow-run-artifacts.js";
import { registerGithubGetActionsCacheUsageForRepoTool } from "./tools/actions/cache/github-get-actions-cache-usage-for-repo.js";
import { registerGithubGetActionsCacheUsageForOrgTool } from "./tools/actions/cache/github-get-actions-cache-usage-for-org.js";
import { registerGithubGetActionsCacheUsageByRepoForOrgTool } from "./tools/actions/cache/github-get-actions-cache-usage-by-repo-for-org.js";
import { registerGithubListActionsCachesTool } from "./tools/actions/cache/github-list-actions-caches.js";
import { registerGithubDeleteActionsCacheByKeyTool } from "./tools/actions/cache/github-delete-actions-cache-by-key.js";
import { registerGithubDeleteActionsCacheByIdTool } from "./tools/actions/cache/github-delete-actions-cache-by-id.js";
import { registerGithubListConcurrencyGroupsForRepoTool } from "./tools/actions/concurrency-groups/github-list-concurrency-groups-for-repo.js";
import { registerGithubGetConcurrencyGroupTool } from "./tools/actions/concurrency-groups/github-get-concurrency-group.js";
import { registerGithubListConcurrencyGroupsForWorkflowRunTool } from "./tools/actions/concurrency-groups/github-list-concurrency-groups-for-workflow-run.js";
import { registerGithubListHostedRunnersForOrgTool } from "./tools/actions/hosted-runners/github-list-hosted-runners-for-org.js";
import { registerGithubCreateHostedRunnerForOrgTool } from "./tools/actions/hosted-runners/github-create-hosted-runner-for-org.js";
import { registerGithubListCustomImagesForOrgTool } from "./tools/actions/hosted-runners/github-list-custom-images-for-org.js";
import { registerGithubGetCustomImageForOrgTool } from "./tools/actions/hosted-runners/github-get-custom-image-for-org.js";
import { registerGithubDeleteCustomImageFromOrgTool } from "./tools/actions/hosted-runners/github-delete-custom-image-from-org.js";
import { registerGithubListCustomImageVersionsForOrgTool } from "./tools/actions/hosted-runners/github-list-custom-image-versions-for-org.js";
import { registerGithubGetCustomImageVersionForOrgTool } from "./tools/actions/hosted-runners/github-get-custom-image-version-for-org.js";
import { registerGithubDeleteCustomImageVersionFromOrgTool } from "./tools/actions/hosted-runners/github-delete-custom-image-version-from-org.js";
import { registerGithubGetHostedRunnersGithubOwnedImagesForOrgTool } from "./tools/actions/hosted-runners/github-get-hosted-runners-github-owned-images-for-org.js";
import { registerGithubGetHostedRunnersPartnerImagesForOrgTool } from "./tools/actions/hosted-runners/github-get-hosted-runners-partner-images-for-org.js";
import { registerGithubGetHostedRunnersLimitsForOrgTool } from "./tools/actions/hosted-runners/github-get-hosted-runners-limits-for-org.js";
import { registerGithubGetHostedRunnersMachineSpecsForOrgTool } from "./tools/actions/hosted-runners/github-get-hosted-runners-machine-specs-for-org.js";
import { registerGithubGetHostedRunnersPlatformsForOrgTool } from "./tools/actions/hosted-runners/github-get-hosted-runners-platforms-for-org.js";
import { registerGithubGetHostedRunnerForOrgTool } from "./tools/actions/hosted-runners/github-get-hosted-runner-for-org.js";
import { registerGithubUpdateHostedRunnerForOrgTool } from "./tools/actions/hosted-runners/github-update-hosted-runner-for-org.js";
import { registerGithubDeleteHostedRunnerForOrgTool } from "./tools/actions/hosted-runners/github-delete-hosted-runner-for-org.js";
import { registerGithubGetOidcCustomSubTemplateForOrgTool } from "./tools/actions/oidc/github-get-oidc-custom-sub-template-for-org.js";
import { registerGithubUpdateOidcCustomSubTemplateForOrgTool } from "./tools/actions/oidc/github-update-oidc-custom-sub-template-for-org.js";
import { registerGithubGetCustomOidcSubClaimForRepoTool } from "./tools/actions/oidc/github-get-custom-oidc-sub-claim-for-repo.js";
import { registerGithubSetCustomOidcSubClaimForRepoTool } from "./tools/actions/oidc/github-set-custom-oidc-sub-claim-for-repo.js";
import { registerGithubGetGithubActionsPermissionsOrganizationTool } from "./tools/actions/permissions/github-get-github-actions-permissions-organization.js";
import { registerGithubSetGithubActionsPermissionsOrganizationTool } from "./tools/actions/permissions/github-set-github-actions-permissions-organization.js";
import { registerGithubListSelectedRepositoriesEnabledGithubActionsOrganizationTool } from "./tools/actions/permissions/github-list-selected-repositories-enabled-github-actions-organization.js";
import { registerGithubSetSelectedRepositoriesEnabledGithubActionsOrganizationTool } from "./tools/actions/permissions/github-set-selected-repositories-enabled-github-actions-organization.js";
import { registerGithubEnableSelectedRepositoryGithubActionsOrganizationTool } from "./tools/actions/permissions/github-enable-selected-repository-github-actions-organization.js";
import { registerGithubDisableSelectedRepositoryGithubActionsOrganizationTool } from "./tools/actions/permissions/github-disable-selected-repository-github-actions-organization.js";
import { registerGithubGetAllowedActionsOrganizationTool } from "./tools/actions/permissions/github-get-allowed-actions-organization.js";
import { registerGithubSetAllowedActionsOrganizationTool } from "./tools/actions/permissions/github-set-allowed-actions-organization.js";
import { registerGithubGetGithubActionsDefaultWorkflowPermissionsOrganizationTool } from "./tools/actions/permissions/github-get-github-actions-default-workflow-permissions-organization.js";
import { registerGithubSetGithubActionsDefaultWorkflowPermissionsOrganizationTool } from "./tools/actions/permissions/github-set-github-actions-default-workflow-permissions-organization.js";
import { registerGithubGetGithubActionsPermissionsRepositoryTool } from "./tools/actions/permissions/github-get-github-actions-permissions-repository.js";
import { registerGithubSetGithubActionsPermissionsRepositoryTool } from "./tools/actions/permissions/github-set-github-actions-permissions-repository.js";
import { registerGithubGetWorkflowAccessToRepositoryTool } from "./tools/actions/permissions/github-get-workflow-access-to-repository.js";
import { registerGithubSetWorkflowAccessToRepositoryTool } from "./tools/actions/permissions/github-set-workflow-access-to-repository.js";
import { registerGithubGetAllowedActionsRepositoryTool } from "./tools/actions/permissions/github-get-allowed-actions-repository.js";
import { registerGithubSetAllowedActionsRepositoryTool } from "./tools/actions/permissions/github-set-allowed-actions-repository.js";
import { registerGithubGetGithubActionsDefaultWorkflowPermissionsRepositoryTool } from "./tools/actions/permissions/github-get-github-actions-default-workflow-permissions-repository.js";
import { registerGithubSetGithubActionsDefaultWorkflowPermissionsRepositoryTool } from "./tools/actions/permissions/github-set-github-actions-default-workflow-permissions-repository.js";
import { registerGithubListOrgActionsSecretsTool } from "./tools/actions/secrets/github-list-org-actions-secrets.js";
import { registerGithubGetOrgActionsPublicKeyTool } from "./tools/actions/secrets/github-get-org-actions-public-key.js";
import { registerGithubGetOrgActionsSecretTool } from "./tools/actions/secrets/github-get-org-actions-secret.js";
import { registerGithubCreateOrUpdateOrgActionsSecretTool } from "./tools/actions/secrets/github-create-or-update-org-actions-secret.js";
import { registerGithubDeleteOrgActionsSecretTool } from "./tools/actions/secrets/github-delete-org-actions-secret.js";
import { registerGithubListSelectedReposForOrgActionsSecretTool } from "./tools/actions/secrets/github-list-selected-repos-for-org-actions-secret.js";
import { registerGithubSetSelectedReposForOrgActionsSecretTool } from "./tools/actions/secrets/github-set-selected-repos-for-org-actions-secret.js";
import { registerGithubAddSelectedRepoToOrgActionsSecretTool } from "./tools/actions/secrets/github-add-selected-repo-to-org-actions-secret.js";
import { registerGithubRemoveSelectedRepoFromOrgActionsSecretTool } from "./tools/actions/secrets/github-remove-selected-repo-from-org-actions-secret.js";
import { registerGithubListRepoOrganizationActionsSecretsTool } from "./tools/actions/secrets/github-list-repo-organization-actions-secrets.js";
import { registerGithubListRepoActionsSecretsTool } from "./tools/actions/secrets/github-list-repo-actions-secrets.js";
import { registerGithubGetRepoActionsPublicKeyTool } from "./tools/actions/secrets/github-get-repo-actions-public-key.js";
import { registerGithubGetRepoActionsSecretTool } from "./tools/actions/secrets/github-get-repo-actions-secret.js";
import { registerGithubCreateOrUpdateRepoActionsSecretTool } from "./tools/actions/secrets/github-create-or-update-repo-actions-secret.js";
import { registerGithubDeleteRepoActionsSecretTool } from "./tools/actions/secrets/github-delete-repo-actions-secret.js";
import { registerGithubListEnvironmentActionsSecretsTool } from "./tools/actions/secrets/github-list-environment-actions-secrets.js";
import { registerGithubGetEnvironmentActionsPublicKeyTool } from "./tools/actions/secrets/github-get-environment-actions-public-key.js";
import { registerGithubGetEnvironmentActionsSecretTool } from "./tools/actions/secrets/github-get-environment-actions-secret.js";
import { registerGithubCreateOrUpdateEnvironmentActionsSecretTool } from "./tools/actions/secrets/github-create-or-update-environment-actions-secret.js";
import { registerGithubDeleteEnvironmentActionsSecretTool } from "./tools/actions/secrets/github-delete-environment-actions-secret.js";
import { registerGithubListSelfHostedRunnerGroupsForOrgTool } from "./tools/actions/runner-groups/github-list-self-hosted-runner-groups-for-org.js";
import { registerGithubCreateSelfHostedRunnerGroupForOrgTool } from "./tools/actions/runner-groups/github-create-self-hosted-runner-group-for-org.js";
import { registerGithubGetSelfHostedRunnerGroupForOrgTool } from "./tools/actions/runner-groups/github-get-self-hosted-runner-group-for-org.js";
import { registerGithubUpdateSelfHostedRunnerGroupForOrgTool } from "./tools/actions/runner-groups/github-update-self-hosted-runner-group-for-org.js";
import { registerGithubDeleteSelfHostedRunnerGroupFromOrgTool } from "./tools/actions/runner-groups/github-delete-self-hosted-runner-group-from-org.js";
import { registerGithubListGithubHostedRunnersInGroupForOrgTool } from "./tools/actions/runner-groups/github-list-github-hosted-runners-in-group-for-org.js";
import { registerGithubListRepoAccessToSelfHostedRunnerGroupInOrgTool } from "./tools/actions/runner-groups/github-list-repo-access-to-self-hosted-runner-group-in-org.js";
import { registerGithubSetRepoAccessToSelfHostedRunnerGroupInOrgTool } from "./tools/actions/runner-groups/github-set-repo-access-to-self-hosted-runner-group-in-org.js";
import { registerGithubAddRepoAccessToSelfHostedRunnerGroupInOrgTool } from "./tools/actions/runner-groups/github-add-repo-access-to-self-hosted-runner-group-in-org.js";
import { registerGithubRemoveRepoAccessToSelfHostedRunnerGroupInOrgTool } from "./tools/actions/runner-groups/github-remove-repo-access-to-self-hosted-runner-group-in-org.js";
import { registerGithubListSelfHostedRunnersInGroupForOrgTool } from "./tools/actions/runner-groups/github-list-self-hosted-runners-in-group-for-org.js";
import { registerGithubSetSelfHostedRunnersInGroupForOrgTool } from "./tools/actions/runner-groups/github-set-self-hosted-runners-in-group-for-org.js";
import { registerGithubAddSelfHostedRunnerToGroupForOrgTool } from "./tools/actions/runner-groups/github-add-self-hosted-runner-to-group-for-org.js";
import { registerGithubRemoveSelfHostedRunnerFromGroupForOrgTool } from "./tools/actions/runner-groups/github-remove-self-hosted-runner-from-group-for-org.js";
import { registerGithubListSelfHostedRunnersForOrgTool } from "./tools/actions/runners/github-list-self-hosted-runners-for-org.js";
import { registerGithubListRunnerApplicationsForOrgTool } from "./tools/actions/runners/github-list-runner-applications-for-org.js";
import { registerGithubGenerateRunnerJitconfigForOrgTool } from "./tools/actions/runners/github-generate-runner-jitconfig-for-org.js";
import { registerGithubCreateRegistrationTokenForOrgTool } from "./tools/actions/runners/github-create-registration-token-for-org.js";
import { registerGithubCreateRemoveTokenForOrgTool } from "./tools/actions/runners/github-create-remove-token-for-org.js";
import { registerGithubGetSelfHostedRunnerForOrgTool } from "./tools/actions/runners/github-get-self-hosted-runner-for-org.js";
import { registerGithubDeleteSelfHostedRunnerFromOrgTool } from "./tools/actions/runners/github-delete-self-hosted-runner-from-org.js";
import { registerGithubListLabelsForSelfHostedRunnerForOrgTool } from "./tools/actions/runners/github-list-labels-for-self-hosted-runner-for-org.js";
import { registerGithubAddCustomLabelsToSelfHostedRunnerForOrgTool } from "./tools/actions/runners/github-add-custom-labels-to-self-hosted-runner-for-org.js";
import { registerGithubSetCustomLabelsForSelfHostedRunnerForOrgTool } from "./tools/actions/runners/github-set-custom-labels-for-self-hosted-runner-for-org.js";
import { registerGithubRemoveAllCustomLabelsFromSelfHostedRunnerForOrgTool } from "./tools/actions/runners/github-remove-all-custom-labels-from-self-hosted-runner-for-org.js";
import { registerGithubRemoveCustomLabelFromSelfHostedRunnerForOrgTool } from "./tools/actions/runners/github-remove-custom-label-from-self-hosted-runner-for-org.js";
import { registerGithubListSelfHostedRunnersForRepoTool } from "./tools/actions/runners/github-list-self-hosted-runners-for-repo.js";
import { registerGithubListRunnerApplicationsForRepoTool } from "./tools/actions/runners/github-list-runner-applications-for-repo.js";
import { registerGithubGenerateRunnerJitconfigForRepoTool } from "./tools/actions/runners/github-generate-runner-jitconfig-for-repo.js";
import { registerGithubCreateRegistrationTokenForRepoTool } from "./tools/actions/runners/github-create-registration-token-for-repo.js";
import { registerGithubCreateRemoveTokenForRepoTool } from "./tools/actions/runners/github-create-remove-token-for-repo.js";
import { registerGithubGetSelfHostedRunnerForRepoTool } from "./tools/actions/runners/github-get-self-hosted-runner-for-repo.js";
import { registerGithubDeleteSelfHostedRunnerFromRepoTool } from "./tools/actions/runners/github-delete-self-hosted-runner-from-repo.js";
import { registerGithubListLabelsForSelfHostedRunnerForRepoTool } from "./tools/actions/runners/github-list-labels-for-self-hosted-runner-for-repo.js";
import { registerGithubAddCustomLabelsToSelfHostedRunnerForRepoTool } from "./tools/actions/runners/github-add-custom-labels-to-self-hosted-runner-for-repo.js";
import { registerGithubSetCustomLabelsForSelfHostedRunnerForRepoTool } from "./tools/actions/runners/github-set-custom-labels-for-self-hosted-runner-for-repo.js";
import { registerGithubRemoveAllCustomLabelsFromSelfHostedRunnerForRepoTool } from "./tools/actions/runners/github-remove-all-custom-labels-from-self-hosted-runner-for-repo.js";
import { registerGithubRemoveCustomLabelFromSelfHostedRunnerForRepoTool } from "./tools/actions/runners/github-remove-custom-label-from-self-hosted-runner-for-repo.js";
import { registerGithubListOrgActionsVariablesTool } from "./tools/actions/variables/github-list-org-actions-variables.js";
import { registerGithubCreateOrgActionsVariableTool } from "./tools/actions/variables/github-create-org-actions-variable.js";
import { registerGithubGetOrgActionsVariableTool } from "./tools/actions/variables/github-get-org-actions-variable.js";
import { registerGithubUpdateOrgActionsVariableTool } from "./tools/actions/variables/github-update-org-actions-variable.js";
import { registerGithubDeleteOrgActionsVariableTool } from "./tools/actions/variables/github-delete-org-actions-variable.js";
import { registerGithubListSelectedReposForOrgActionsVariableTool } from "./tools/actions/variables/github-list-selected-repos-for-org-actions-variable.js";
import { registerGithubSetSelectedReposForOrgActionsVariableTool } from "./tools/actions/variables/github-set-selected-repos-for-org-actions-variable.js";
import { registerGithubAddSelectedRepoToOrgActionsVariableTool } from "./tools/actions/variables/github-add-selected-repo-to-org-actions-variable.js";
import { registerGithubRemoveSelectedRepoFromOrgActionsVariableTool } from "./tools/actions/variables/github-remove-selected-repo-from-org-actions-variable.js";
import { registerGithubListRepoOrganizationActionsVariablesTool } from "./tools/actions/variables/github-list-repo-organization-actions-variables.js";
import { registerGithubListRepoActionsVariablesTool } from "./tools/actions/variables/github-list-repo-actions-variables.js";
import { registerGithubCreateRepoActionsVariableTool } from "./tools/actions/variables/github-create-repo-actions-variable.js";
import { registerGithubGetRepoActionsVariableTool } from "./tools/actions/variables/github-get-repo-actions-variable.js";
import { registerGithubUpdateRepoActionsVariableTool } from "./tools/actions/variables/github-update-repo-actions-variable.js";
import { registerGithubDeleteRepoActionsVariableTool } from "./tools/actions/variables/github-delete-repo-actions-variable.js";
import { registerGithubListEnvironmentActionsVariablesTool } from "./tools/actions/variables/github-list-environment-actions-variables.js";
import { registerGithubCreateEnvironmentActionsVariableTool } from "./tools/actions/variables/github-create-environment-actions-variable.js";
import { registerGithubGetEnvironmentActionsVariableTool } from "./tools/actions/variables/github-get-environment-actions-variable.js";
import { registerGithubUpdateEnvironmentActionsVariableTool } from "./tools/actions/variables/github-update-environment-actions-variable.js";
import { registerGithubDeleteEnvironmentActionsVariableTool } from "./tools/actions/variables/github-delete-environment-actions-variable.js";
import { registerGithubGetJobForWorkflowRunTool } from "./tools/actions/workflow-jobs/github-get-job-for-workflow-run.js";
import { registerGithubDownloadJobLogsForWorkflowRunTool } from "./tools/actions/workflow-jobs/github-download-job-logs-for-workflow-run.js";
import { registerGithubListJobsForWorkflowRunAttemptTool } from "./tools/actions/workflow-jobs/github-list-jobs-for-workflow-run-attempt.js";
import { registerGithubListJobsForWorkflowRunTool } from "./tools/actions/workflow-jobs/github-list-jobs-for-workflow-run.js";
import { registerGithubReRunJobForWorkflowRunTool } from "./tools/actions/workflow-runs/github-re-run-job-for-workflow-run.js";
import { registerGithubListWorkflowRunsForRepoTool } from "./tools/actions/workflow-runs/github-list-workflow-runs-for-repo.js";
import { registerGithubGetWorkflowRunTool } from "./tools/actions/workflow-runs/github-get-workflow-run.js";
import { registerGithubDeleteWorkflowRunTool } from "./tools/actions/workflow-runs/github-delete-workflow-run.js";
import { registerGithubGetReviewsForWorkflowRunTool } from "./tools/actions/workflow-runs/github-get-reviews-for-workflow-run.js";
import { registerGithubApproveWorkflowRunTool } from "./tools/actions/workflow-runs/github-approve-workflow-run.js";
import { registerGithubGetWorkflowRunAttemptTool } from "./tools/actions/workflow-runs/github-get-workflow-run-attempt.js";
import { registerGithubDownloadWorkflowRunAttemptLogsTool } from "./tools/actions/workflow-runs/github-download-workflow-run-attempt-logs.js";
import { registerGithubCancelWorkflowRunTool } from "./tools/actions/workflow-runs/github-cancel-workflow-run.js";
import { registerGithubReviewCustomGatesForWorkflowRunTool } from "./tools/actions/workflow-runs/github-review-custom-gates-for-workflow-run.js";
import { registerGithubForceCancelWorkflowRunTool } from "./tools/actions/workflow-runs/github-force-cancel-workflow-run.js";
import { registerGithubDownloadWorkflowRunLogsTool } from "./tools/actions/workflow-runs/github-download-workflow-run-logs.js";
import { registerGithubDeleteWorkflowRunLogsTool } from "./tools/actions/workflow-runs/github-delete-workflow-run-logs.js";
import { registerGithubGetPendingDeploymentsForWorkflowRunTool } from "./tools/actions/workflow-runs/github-get-pending-deployments-for-workflow-run.js";
import { registerGithubReviewPendingDeploymentsForWorkflowRunTool } from "./tools/actions/workflow-runs/github-review-pending-deployments-for-workflow-run.js";
import { registerGithubReRunWorkflowTool } from "./tools/actions/workflow-runs/github-re-run-workflow.js";
import { registerGithubReRunWorkflowFailedJobsTool } from "./tools/actions/workflow-runs/github-re-run-workflow-failed-jobs.js";
import { registerGithubGetWorkflowRunUsageTool } from "./tools/actions/workflow-runs/github-get-workflow-run-usage.js";
import { registerGithubListWorkflowRunsTool } from "./tools/actions/workflow-runs/github-list-workflow-runs.js";
import { registerGithubListRepoWorkflowsTool } from "./tools/actions/workflows/github-list-repo-workflows.js";
import { registerGithubGetWorkflowTool } from "./tools/actions/workflows/github-get-workflow.js";
import { registerGithubDisableWorkflowTool } from "./tools/actions/workflows/github-disable-workflow.js";
import { registerGithubCreateWorkflowDispatchTool } from "./tools/actions/workflows/github-create-workflow-dispatch.js";
import { registerGithubEnableWorkflowTool } from "./tools/actions/workflows/github-enable-workflow.js";
import { registerGithubGetWorkflowUsageTool } from "./tools/actions/workflows/github-get-workflow-usage.js";
import { registerGithubListPublicEventsTool } from "./tools/activity/events/github-list-public-events.js";
import { registerGithubListPublicEventsForRepoNetworkTool } from "./tools/activity/events/github-list-public-events-for-repo-network.js";
import { registerGithubListPublicOrgEventsTool } from "./tools/activity/events/github-list-public-org-events.js";
import { registerGithubListRepoEventsTool } from "./tools/activity/events/github-list-repo-events.js";
import { registerGithubListEventsForAuthenticatedUserTool } from "./tools/activity/events/github-list-events-for-authenticated-user.js";
import { registerGithubListOrgEventsForAuthenticatedUserTool } from "./tools/activity/events/github-list-org-events-for-authenticated-user.js";
import { registerGithubListPublicEventsForUserTool } from "./tools/activity/events/github-list-public-events-for-user.js";
import { registerGithubListReceivedEventsForUserTool } from "./tools/activity/events/github-list-received-events-for-user.js";
import { registerGithubListReceivedPublicEventsForUserTool } from "./tools/activity/events/github-list-received-public-events-for-user.js";
import { registerGithubReplaceRepoTopicsTool } from "./tools/repositories/github-replace-repo-topics.js";
import { registerGithubTransferRepoTool } from "./tools/repositories/github-transfer-repo.js";
import { registerGithubUpdateRepoTool } from "./tools/repositories/github-update-repo.js";

const token = getRequiredEnv("GITHUB_TOKEN");
const octokit = new Octokit({
    auth: token,
    headers: { "X-GitHub-Api-Version": "2026-03-10" }
});
const server = new McpServer({ name: "github-mcp", version: "1.0.0" });

// Register all MCP tools here; each tool implementation lives in its own file.
registerGithubCreatePersonalRepoTool(server, octokit);
registerGithubCreateOrgRepoTool(server, octokit);
registerGithubListOrganizationsTool(server, octokit);
registerGithubListOrgsForAuthenticatedUserTool(server, octokit);
registerGithubListOrgMembershipsForAuthUserTool(server, octokit);
registerGithubGetOrgMembershipForAuthUserTool(server, octokit);
registerGithubUpdateOrgMembershipForAuthUserTool(server, octokit);
registerGithubListOrgsForUserTool(server, octokit);
registerGithubListOrgAppInstallationsTool(server, octokit);
registerGithubListOrgNetworkConfigurationsTool(server, octokit);
registerGithubCreateOrgNetworkConfigurationTool(server, octokit);
registerGithubGetOrgNetworkConfigurationTool(server, octokit);
registerGithubUpdateOrgNetworkConfigurationTool(server, octokit);
registerGithubDeleteOrgNetworkConfigurationTool(server, octokit);
registerGithubGetOrgNetworkSettingsTool(server, octokit);
registerGithubListOrgRolesTool(server, octokit);
registerGithubRemoveAllOrgRolesForTeamTool(server, octokit);
registerGithubAssignOrgRoleToTeamTool(server, octokit);
registerGithubRemoveOrgRoleFromTeamTool(server, octokit);
registerGithubRemoveAllOrgRolesForUserTool(server, octokit);
registerGithubAssignOrgRoleToUserTool(server, octokit);
registerGithubRemoveOrgRoleFromUserTool(server, octokit);
registerGithubGetOrgRoleTool(server, octokit);
registerGithubListTeamsAssignedToOrgRoleTool(server, octokit);
registerGithubListUsersAssignedToOrgRoleTool(server, octokit);
registerGithubListOrgOutsideCollaboratorsTool(server, octokit);
registerGithubConvertOrgMemberToOutsideCollaboratorTool(server, octokit);
registerGithubRemoveOrgOutsideCollaboratorTool(server, octokit);
registerGithubListOrgPatRequestsTool(server, octokit);
registerGithubReviewOrgPatRequestsTool(server, octokit);
registerGithubReviewOrgPatRequestTool(server, octokit);
registerGithubListOrgPatRequestRepositoriesTool(server, octokit);
registerGithubListOrgPatsTool(server, octokit);
registerGithubUpdateOrgPatsTool(server, octokit);
registerGithubUpdateOrgPatTool(server, octokit);
registerGithubListOrgPatRepositoriesTool(server, octokit);
registerGithubListOrgRuleSuitesTool(server, octokit);
registerGithubGetOrgRuleSuiteTool(server, octokit);
registerGithubListOrgRulesetsTool(server, octokit);
registerGithubCreateOrgRulesetTool(server, octokit);
registerGithubGetOrgRulesetTool(server, octokit);
registerGithubUpdateOrgRulesetTool(server, octokit);
registerGithubDeleteOrgRulesetTool(server, octokit);
registerGithubGetOrgRulesetHistoryTool(server, octokit);
registerGithubGetOrgRulesetVersionTool(server, octokit);
registerGithubAddOrgSecurityManagerTeamTool(server, octokit);
registerGithubListOrgSecurityManagerTeamsTool(server, octokit);
registerGithubRemoveOrgSecurityManagerTeamTool(server, octokit);
registerGithubCreateOrgWebhookTool(server, octokit);
registerGithubDeleteOrgWebhookTool(server, octokit);
registerGithubGetOrgWebhookDeliveryTool(server, octokit);
registerGithubGetOrgWebhookConfigTool(server, octokit);
registerGithubGetOrgWebhookTool(server, octokit);
registerGithubListOrgWebhookDeliveriesTool(server, octokit);
registerGithubPingOrgWebhookTool(server, octokit);
registerGithubRedeliverOrgWebhookDeliveryTool(server, octokit);
registerGithubListOrgWebhooksTool(server, octokit);
registerGithubUpdateOrgWebhookConfigTool(server, octokit);
registerGithubUpdateOrgWebhookTool(server, octokit);
registerGithubGetOrgTool(server, octokit);
registerGithubListOrgIssueFieldsTool(server, octokit);
registerGithubCreateOrgIssueFieldTool(server, octokit);
registerGithubUpdateOrgIssueFieldTool(server, octokit);
registerGithubDeleteOrgIssueFieldTool(server, octokit);
registerGithubListOrgIssueTypesTool(server, octokit);
registerGithubCreateOrgIssueTypeTool(server, octokit);
registerGithubUpdateOrgIssueTypeTool(server, octokit);
registerGithubDeleteOrgIssueTypeTool(server, octokit);
registerGithubGetOrgCustomPropertiesTool(server, octokit);
registerGithubGetOrgCustomPropertyTool(server, octokit);
registerGithubCreateUpdateOrgCustomPropertiesTool(server, octokit);
registerGithubCreateUpdateOrgCustomPropertyTool(server, octokit);
registerGithubDeleteOrgCustomPropertyTool(server, octokit);
registerGithubListOrgCustomPropertyValuesTool(server, octokit);
registerGithubCreateUpdateOrgCustomPropertyValuesTool(server, octokit);
registerGithubGetOrgRouteStatsByActorTool(server, octokit);
registerGithubGetOrgSubjectStatsTool(server, octokit);
registerGithubGetOrgSummaryStatsTool(server, octokit);
registerGithubGetOrgSummaryStatsByActorTool(server, octokit);
registerGithubGetOrgSummaryStatsByUserTool(server, octokit);
registerGithubGetOrgTimeStatsTool(server, octokit);
registerGithubGetOrgTimeStatsByActorTool(server, octokit);
registerGithubGetOrgTimeStatsByUserTool(server, octokit);
registerGithubGetOrgUserStatsTool(server, octokit);
registerGithubGetOrgImmutableReleasesSettingsTool(server, octokit);
registerGithubSetOrgImmutableReleasesSettingsTool(server, octokit);
registerGithubListImmutableReleasesForOrgReposTool(server, octokit);
registerGithubEnableImmutableReleasesForOrgRepoTool(server, octokit);
registerGithubEnableOrDisableOrgSecurityFeatureTool(server, octokit);
registerGithubCreateOrgArtifactDeploymentRecordTool(server, octokit);
registerGithubCreateOrgMetadataStorageRecordTool(server, octokit);
registerGithubListOrgArtifactDeploymentRecordsTool(server, octokit);
registerGithubListOrgMetadataStorageRecordsTool(server, octokit);
registerGithubListOrgAttestationReposTool(server, octokit);
registerGithubListOrgAttestationsTool(server, octokit);
registerGithubListOrgAttestationsBulkSubjectDigestsTool(server, octokit);
registerGithubListOrgBlockedUsersTool(server, octokit);
registerGithubListOrgFailedInvitationsTool(server, octokit);
registerGithubListOrgPendingInvitationsTool(server, octokit);
registerGithubListOrgInvitationTeamsTool(server, octokit);
registerGithubCreateOrgInvitationTool(server, octokit);
registerGithubCancelOrgInvitationTool(server, octokit);
registerGithubListOrgMembersTool(server, octokit);
registerGithubListOrgPublicMembersTool(server, octokit);
registerGithubCheckOrgPublicMembershipForUserTool(server, octokit);
registerGithubSetPublicOrgMembershipForAuthUserTool(server, octokit);
registerGithubRemovePublicOrgMembershipForAuthUserTool(server, octokit);
registerGithubCheckOrgMembershipForUserTool(server, octokit);
registerGithubRemoveOrgMemberTool(server, octokit);
registerGithubGetOrgMembershipForUserTool(server, octokit);
registerGithubSetOrgMembershipForUserTool(server, octokit);
registerGithubRemoveOrgMembershipForUserTool(server, octokit);
registerGithubCheckOrgBlockedUserTool(server, octokit);
registerGithubBlockOrgUserTool(server, octokit);
registerGithubUnblockOrgUserTool(server, octokit);
registerGithubDeleteOrgAttestationByIdTool(server, octokit);
registerGithubDeleteOrgAttestationBySubjectDigestTool(server, octokit);
registerGithubDeleteOrgAttestationsBulkTool(server, octokit);
registerGithubSetOrgClusterDeploymentRecordsTool(server, octokit);
registerGithubDisableImmutableReleasesForOrgRepoTool(server, octokit);
registerGithubSetImmutableReleasesForOrgReposTool(server, octokit);
registerGithubUpdateOrgTool(server, octokit);
registerGithubDeleteOrgTool(server, octokit);
registerGithubListOrgReposTool(server, octokit);
registerGithubCreateRepoFromTemplateTool(server, octokit);
registerGithubDeleteRepoTool(server, octokit);
registerGithubCheckDependabotSecurityUpdatesTool(server, octokit);
registerGithubCheckPrivateVulnerabilityReportingTool(server, octokit);
registerGithubCheckImmutableReleasesTool(server, octokit);
registerGithubEnableImmutableReleasesTool(server, octokit);
registerGithubDisableImmutableReleasesTool(server, octokit);
registerGithubCheckVulnerabilityAlertsTool(server, octokit);
registerGithubEnableVulnerabilityAlertsTool(server, octokit);
registerGithubDisableVulnerabilityAlertsTool(server, octokit);
registerGithubEnablePrivateVulnerabilityReportingTool(server, octokit);
registerGithubDisablePrivateVulnerabilityReportingTool(server, octokit);
registerGithubEnableDependabotSecurityUpdatesTool(server, octokit);
registerGithubDisableDependabotSecurityUpdatesTool(server, octokit);
registerGithubGetRepoTool(server, octokit);
registerGithubGetRepoContentTool(server, octokit);
registerGithubGetRepoReadmeTool(server, octokit);
registerGithubGetRepoReadmeInDirectoryTool(server, octokit);
registerGithubCreateUpdateFileContentsTool(server, octokit);
registerGithubDeleteFileTool(server, octokit);
registerGithubDownloadRepoArchiveTarTool(server, octokit);
registerGithubDownloadRepoArchiveZipTool(server, octokit);
registerGithubListRepoAutolinksTool(server, octokit);
registerGithubCreateRepoAutolinkTool(server, octokit);
registerGithubGetRepoAutolinkTool(server, octokit);
registerGithubDeleteRepoAutolinkTool(server, octokit);
registerGithubGetRepoCustomPropertyValuesTool(server, octokit);
registerGithubCreateUpdateRepoCustomPropertyValuesTool(server, octokit);
registerGithubListCodeownersErrorsTool(server, octokit);
registerGithubListRepoContributorsTool(server, octokit);
registerGithubListRepoActivitiesTool(server, octokit);
registerGithubListAuthenticatedUserReposTool(server, octokit);
registerGithubListPublicReposTool(server, octokit);
registerGithubListRepoLanguagesTool(server, octokit);
registerGithubListRepoForksTool(server, octokit);
registerGithubListRepoRuleSuitesTool(server, octokit);
registerGithubGetRepoRuleSuiteTool(server, octokit);
registerGithubGetRepoBranchRulesTool(server, octokit);
registerGithubListRepoRulesetsTool(server, octokit);
registerGithubGetRepoRulesetTool(server, octokit);
registerGithubGetRepoRulesetHistoryTool(server, octokit);
registerGithubGetRepoRulesetVersionTool(server, octokit);
registerGithubCreateRepoRulesetTool(server, octokit);
registerGithubUpdateRepoRulesetTool(server, octokit);
registerGithubDeleteRepoRulesetTool(server, octokit);
registerGithubCreateRepoForkTool(server, octokit);
registerGithubListRepoTagsTool(server, octokit);
registerGithubListRepoTeamsTool(server, octokit);
registerGithubListRepoTopicsTool(server, octokit);
registerGithubListUserReposTool(server, octokit);
registerGithubReplaceRepoTopicsTool(server, octokit);
registerGithubTransferRepoTool(server, octokit);
registerGithubUpdateRepoTool(server, octokit);
registerGithubCreateRepoDispatchTool(server, octokit);
registerGithubCreateRepoAttestationTool(server, octokit);
registerGithubListRepoAttestationsTool(server, octokit);
registerGithubListRepoWebhooksTool(server, octokit);
registerGithubListRepoWebhookDeliveriesTool(server, octokit);
registerGithubGetRepoWebhookDeliveryTool(server, octokit);
registerGithubRedeliverRepoWebhookDeliveryTool(server, octokit);
registerGithubPingRepoWebhookTool(server, octokit);
registerGithubTestPushRepoWebhookTool(server, octokit);
registerGithubGetRepoWebhookTool(server, octokit);
registerGithubGetRepoWebhookConfigTool(server, octokit);
registerGithubCreateRepoWebhookTool(server, octokit);
registerGithubUpdateRepoWebhookConfigTool(server, octokit);
registerGithubUpdateRepoWebhookTool(server, octokit);
registerGithubDeleteRepoWebhookTool(server, octokit);
registerGithubListArtifactsForRepoTool(server, octokit);
registerGithubGetArtifactTool(server, octokit);
registerGithubDeleteArtifactTool(server, octokit);
registerGithubDownloadArtifactTool(server, octokit);
registerGithubListWorkflowRunArtifactsTool(server, octokit);
registerGithubGetActionsCacheUsageForRepoTool(server, octokit);
registerGithubGetActionsCacheUsageForOrgTool(server, octokit);
registerGithubGetActionsCacheUsageByRepoForOrgTool(server, octokit);
registerGithubListActionsCachesTool(server, octokit);
registerGithubDeleteActionsCacheByKeyTool(server, octokit);
registerGithubDeleteActionsCacheByIdTool(server, octokit);
registerGithubListConcurrencyGroupsForRepoTool(server, octokit);
registerGithubGetConcurrencyGroupTool(server, octokit);
registerGithubListConcurrencyGroupsForWorkflowRunTool(server, octokit);
registerGithubListHostedRunnersForOrgTool(server, octokit);
registerGithubCreateHostedRunnerForOrgTool(server, octokit);
registerGithubListCustomImagesForOrgTool(server, octokit);
registerGithubGetCustomImageForOrgTool(server, octokit);
registerGithubDeleteCustomImageFromOrgTool(server, octokit);
registerGithubListCustomImageVersionsForOrgTool(server, octokit);
registerGithubGetCustomImageVersionForOrgTool(server, octokit);
registerGithubDeleteCustomImageVersionFromOrgTool(server, octokit);
registerGithubGetHostedRunnersGithubOwnedImagesForOrgTool(server, octokit);
registerGithubGetHostedRunnersPartnerImagesForOrgTool(server, octokit);
registerGithubGetHostedRunnersLimitsForOrgTool(server, octokit);
registerGithubGetHostedRunnersMachineSpecsForOrgTool(server, octokit);
registerGithubGetHostedRunnersPlatformsForOrgTool(server, octokit);
registerGithubGetHostedRunnerForOrgTool(server, octokit);
registerGithubUpdateHostedRunnerForOrgTool(server, octokit);
registerGithubDeleteHostedRunnerForOrgTool(server, octokit);
registerGithubGetOidcCustomSubTemplateForOrgTool(server, octokit);
registerGithubUpdateOidcCustomSubTemplateForOrgTool(server, octokit);
registerGithubGetCustomOidcSubClaimForRepoTool(server, octokit);
registerGithubSetCustomOidcSubClaimForRepoTool(server, octokit);
registerGithubGetGithubActionsPermissionsOrganizationTool(server, octokit);
registerGithubSetGithubActionsPermissionsOrganizationTool(server, octokit);
registerGithubListSelectedRepositoriesEnabledGithubActionsOrganizationTool(server, octokit);
registerGithubSetSelectedRepositoriesEnabledGithubActionsOrganizationTool(server, octokit);
registerGithubEnableSelectedRepositoryGithubActionsOrganizationTool(server, octokit);
registerGithubDisableSelectedRepositoryGithubActionsOrganizationTool(server, octokit);
registerGithubGetAllowedActionsOrganizationTool(server, octokit);
registerGithubSetAllowedActionsOrganizationTool(server, octokit);
registerGithubGetGithubActionsDefaultWorkflowPermissionsOrganizationTool(server, octokit);
registerGithubSetGithubActionsDefaultWorkflowPermissionsOrganizationTool(server, octokit);
registerGithubGetGithubActionsPermissionsRepositoryTool(server, octokit);
registerGithubSetGithubActionsPermissionsRepositoryTool(server, octokit);
registerGithubGetWorkflowAccessToRepositoryTool(server, octokit);
registerGithubSetWorkflowAccessToRepositoryTool(server, octokit);
registerGithubGetAllowedActionsRepositoryTool(server, octokit);
registerGithubSetAllowedActionsRepositoryTool(server, octokit);
registerGithubGetGithubActionsDefaultWorkflowPermissionsRepositoryTool(server, octokit);
registerGithubSetGithubActionsDefaultWorkflowPermissionsRepositoryTool(server, octokit);
registerGithubListOrgActionsSecretsTool(server, octokit);
registerGithubGetOrgActionsPublicKeyTool(server, octokit);
registerGithubGetOrgActionsSecretTool(server, octokit);
registerGithubCreateOrUpdateOrgActionsSecretTool(server, octokit);
registerGithubDeleteOrgActionsSecretTool(server, octokit);
registerGithubListSelectedReposForOrgActionsSecretTool(server, octokit);
registerGithubSetSelectedReposForOrgActionsSecretTool(server, octokit);
registerGithubAddSelectedRepoToOrgActionsSecretTool(server, octokit);
registerGithubRemoveSelectedRepoFromOrgActionsSecretTool(server, octokit);
registerGithubListRepoOrganizationActionsSecretsTool(server, octokit);
registerGithubListRepoActionsSecretsTool(server, octokit);
registerGithubGetRepoActionsPublicKeyTool(server, octokit);
registerGithubGetRepoActionsSecretTool(server, octokit);
registerGithubCreateOrUpdateRepoActionsSecretTool(server, octokit);
registerGithubDeleteRepoActionsSecretTool(server, octokit);
registerGithubListEnvironmentActionsSecretsTool(server, octokit);
registerGithubGetEnvironmentActionsPublicKeyTool(server, octokit);
registerGithubGetEnvironmentActionsSecretTool(server, octokit);
registerGithubCreateOrUpdateEnvironmentActionsSecretTool(server, octokit);
registerGithubDeleteEnvironmentActionsSecretTool(server, octokit);
registerGithubListSelfHostedRunnerGroupsForOrgTool(server, octokit);
registerGithubCreateSelfHostedRunnerGroupForOrgTool(server, octokit);
registerGithubGetSelfHostedRunnerGroupForOrgTool(server, octokit);
registerGithubUpdateSelfHostedRunnerGroupForOrgTool(server, octokit);
registerGithubDeleteSelfHostedRunnerGroupFromOrgTool(server, octokit);
registerGithubListGithubHostedRunnersInGroupForOrgTool(server, octokit);
registerGithubListRepoAccessToSelfHostedRunnerGroupInOrgTool(server, octokit);
registerGithubSetRepoAccessToSelfHostedRunnerGroupInOrgTool(server, octokit);
registerGithubAddRepoAccessToSelfHostedRunnerGroupInOrgTool(server, octokit);
registerGithubRemoveRepoAccessToSelfHostedRunnerGroupInOrgTool(server, octokit);
registerGithubListSelfHostedRunnersInGroupForOrgTool(server, octokit);
registerGithubSetSelfHostedRunnersInGroupForOrgTool(server, octokit);
registerGithubAddSelfHostedRunnerToGroupForOrgTool(server, octokit);
registerGithubRemoveSelfHostedRunnerFromGroupForOrgTool(server, octokit);
registerGithubListSelfHostedRunnersForOrgTool(server, octokit);
registerGithubListRunnerApplicationsForOrgTool(server, octokit);
registerGithubGenerateRunnerJitconfigForOrgTool(server, octokit);
registerGithubCreateRegistrationTokenForOrgTool(server, octokit);
registerGithubCreateRemoveTokenForOrgTool(server, octokit);
registerGithubGetSelfHostedRunnerForOrgTool(server, octokit);
registerGithubDeleteSelfHostedRunnerFromOrgTool(server, octokit);
registerGithubListLabelsForSelfHostedRunnerForOrgTool(server, octokit);
registerGithubAddCustomLabelsToSelfHostedRunnerForOrgTool(server, octokit);
registerGithubSetCustomLabelsForSelfHostedRunnerForOrgTool(server, octokit);
registerGithubRemoveAllCustomLabelsFromSelfHostedRunnerForOrgTool(server, octokit);
registerGithubRemoveCustomLabelFromSelfHostedRunnerForOrgTool(server, octokit);
registerGithubListSelfHostedRunnersForRepoTool(server, octokit);
registerGithubListRunnerApplicationsForRepoTool(server, octokit);
registerGithubGenerateRunnerJitconfigForRepoTool(server, octokit);
registerGithubCreateRegistrationTokenForRepoTool(server, octokit);
registerGithubCreateRemoveTokenForRepoTool(server, octokit);
registerGithubGetSelfHostedRunnerForRepoTool(server, octokit);
registerGithubDeleteSelfHostedRunnerFromRepoTool(server, octokit);
registerGithubListLabelsForSelfHostedRunnerForRepoTool(server, octokit);
registerGithubAddCustomLabelsToSelfHostedRunnerForRepoTool(server, octokit);
registerGithubSetCustomLabelsForSelfHostedRunnerForRepoTool(server, octokit);
registerGithubRemoveAllCustomLabelsFromSelfHostedRunnerForRepoTool(server, octokit);
registerGithubRemoveCustomLabelFromSelfHostedRunnerForRepoTool(server, octokit);
registerGithubListOrgActionsVariablesTool(server, octokit);
registerGithubCreateOrgActionsVariableTool(server, octokit);
registerGithubGetOrgActionsVariableTool(server, octokit);
registerGithubUpdateOrgActionsVariableTool(server, octokit);
registerGithubDeleteOrgActionsVariableTool(server, octokit);
registerGithubListSelectedReposForOrgActionsVariableTool(server, octokit);
registerGithubSetSelectedReposForOrgActionsVariableTool(server, octokit);
registerGithubAddSelectedRepoToOrgActionsVariableTool(server, octokit);
registerGithubRemoveSelectedRepoFromOrgActionsVariableTool(server, octokit);
registerGithubListRepoOrganizationActionsVariablesTool(server, octokit);
registerGithubListRepoActionsVariablesTool(server, octokit);
registerGithubCreateRepoActionsVariableTool(server, octokit);
registerGithubGetRepoActionsVariableTool(server, octokit);
registerGithubUpdateRepoActionsVariableTool(server, octokit);
registerGithubDeleteRepoActionsVariableTool(server, octokit);
registerGithubListEnvironmentActionsVariablesTool(server, octokit);
registerGithubCreateEnvironmentActionsVariableTool(server, octokit);
registerGithubGetEnvironmentActionsVariableTool(server, octokit);
registerGithubUpdateEnvironmentActionsVariableTool(server, octokit);
registerGithubDeleteEnvironmentActionsVariableTool(server, octokit);
registerGithubGetJobForWorkflowRunTool(server, octokit);
registerGithubDownloadJobLogsForWorkflowRunTool(server, octokit);
registerGithubListJobsForWorkflowRunAttemptTool(server, octokit);
registerGithubListJobsForWorkflowRunTool(server, octokit);
registerGithubReRunJobForWorkflowRunTool(server, octokit);
registerGithubListWorkflowRunsForRepoTool(server, octokit);
registerGithubGetWorkflowRunTool(server, octokit);
registerGithubDeleteWorkflowRunTool(server, octokit);
registerGithubGetReviewsForWorkflowRunTool(server, octokit);
registerGithubApproveWorkflowRunTool(server, octokit);
registerGithubGetWorkflowRunAttemptTool(server, octokit);
registerGithubDownloadWorkflowRunAttemptLogsTool(server, octokit);
registerGithubCancelWorkflowRunTool(server, octokit);
registerGithubReviewCustomGatesForWorkflowRunTool(server, octokit);
registerGithubForceCancelWorkflowRunTool(server, octokit);
registerGithubDownloadWorkflowRunLogsTool(server, octokit);
registerGithubDeleteWorkflowRunLogsTool(server, octokit);
registerGithubGetPendingDeploymentsForWorkflowRunTool(server, octokit);
registerGithubReviewPendingDeploymentsForWorkflowRunTool(server, octokit);
registerGithubReRunWorkflowTool(server, octokit);
registerGithubReRunWorkflowFailedJobsTool(server, octokit);
registerGithubGetWorkflowRunUsageTool(server, octokit);
registerGithubListWorkflowRunsTool(server, octokit);
registerGithubListRepoWorkflowsTool(server, octokit);
registerGithubGetWorkflowTool(server, octokit);
registerGithubDisableWorkflowTool(server, octokit);
registerGithubCreateWorkflowDispatchTool(server, octokit);
registerGithubEnableWorkflowTool(server, octokit);
registerGithubGetWorkflowUsageTool(server, octokit);
registerGithubListPublicEventsTool(server, octokit);
registerGithubListPublicEventsForRepoNetworkTool(server, octokit);
registerGithubListPublicOrgEventsTool(server, octokit);
registerGithubListRepoEventsTool(server, octokit);
registerGithubListEventsForAuthenticatedUserTool(server, octokit);
registerGithubListOrgEventsForAuthenticatedUserTool(server, octokit);
registerGithubListPublicEventsForUserTool(server, octokit);
registerGithubListReceivedEventsForUserTool(server, octokit);
registerGithubListReceivedPublicEventsForUserTool(server, octokit);

async function main() {
    const transport = new StdioServerTransport();
    await server.connect(transport);
}

main().catch((error) => {
    // Keep startup failures explicit for MCP client logs.
    console.error("Failed to start github-mcp server:", error);
    process.exit(1);
});
