import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { Octokit } from "@octokit/rest";
import { getRequiredEnv } from "./config/env.js";
import { registerGithubCheckDependabotSecurityUpdatesTool } from "./tools/repositories/github-check-dependabot-security-updates.js";
import { registerGithubCheckPrivateVulnerabilityReportingTool } from "./tools/repositories/github-check-private-vulnerability-reporting.js";
import { registerGithubCheckImmutableReleasesTool } from "./tools/repositories/github-check-immutable-releases.js";
import { registerGithubCheckVulnerabilityAlertsTool } from "./tools/repositories/github-check-vulnerability-alerts.js";
import { registerGithubEnableImmutableReleasesTool } from "./tools/repositories/github-enable-immutable-releases.js";
import { registerGithubDisableImmutableReleasesTool } from "./tools/repositories/github-disable-immutable-releases.js";
import { registerGithubDisableDependabotSecurityUpdatesTool } from "./tools/repositories/github-disable-dependabot-security-updates.js";
import { registerGithubEnableDependabotSecurityUpdatesTool } from "./tools/repositories/github-enable-dependabot-security-updates.js";
import { registerGithubDisablePrivateVulnerabilityReportingTool } from "./tools/repositories/github-disable-private-vulnerability-reporting.js";
import { registerGithubEnablePrivateVulnerabilityReportingTool } from "./tools/repositories/github-enable-private-vulnerability-reporting.js";
import { registerGithubDisableVulnerabilityAlertsTool } from "./tools/repositories/github-disable-vulnerability-alerts.js";
import { registerGithubEnableVulnerabilityAlertsTool } from "./tools/repositories/github-enable-vulnerability-alerts.js";
import { registerGithubCreateOrgRepoTool } from "./tools/repositories/github-create-org-repo.js";
import { registerGithubCreatePersonalRepoTool } from "./tools/repositories/github-create-personal-repo.js";
import { registerGithubCreateRepoFromTemplateTool } from "./tools/repositories/github-create-repo-from-template.js";
import { registerGithubCreateRepoAttestationTool } from "./tools/repositories/attestations/github-create-repo-attestation.js";
import { registerGithubListRepoAttestationsTool } from "./tools/repositories/attestations/github-list-repo-attestations.js";
import { registerGithubCreateRepoAutolinkTool } from "./tools/repositories/autolinks/github-create-repo-autolink.js";
import { registerGithubDeleteRepoAutolinkTool } from "./tools/repositories/autolinks/github-delete-repo-autolink.js";
import { registerGithubGetRepoAutolinkTool } from "./tools/repositories/autolinks/github-get-repo-autolink.js";
import { registerGithubListRepoAutolinksTool } from "./tools/repositories/autolinks/github-list-repo-autolinks.js";
import { registerGithubCreateUpdateRepoCustomPropertyValuesTool } from "./tools/repositories/custom-properties/github-create-update-repo-custom-property-values.js";
import { registerGithubGetRepoCustomPropertyValuesTool } from "./tools/repositories/custom-properties/github-get-repo-custom-property-values.js";
import { registerGithubCreateRepoDispatchTool } from "./tools/repositories/github-create-repo-dispatch.js";
import { registerGithubDeleteRepoTool } from "./tools/repositories/github-delete-repo.js";
import { registerGithubGetRepoTool } from "./tools/repositories/github-get-repo.js";
import { registerGithubCreateUpdateFileContentsTool } from "./tools/repositories/contents/github-create-update-file-contents.js";
import { registerGithubDeleteFileTool } from "./tools/repositories/contents/github-delete-file.js";
import { registerGithubDownloadRepoArchiveTarTool } from "./tools/repositories/contents/github-download-repo-archive-tar.js";
import { registerGithubDownloadRepoArchiveZipTool } from "./tools/repositories/contents/github-download-repo-archive-zip.js";
import { registerGithubGetRepoContentTool } from "./tools/repositories/contents/github-get-repo-content.js";
import { registerGithubGetRepoReadmeTool } from "./tools/repositories/contents/github-get-repo-readme.js";
import { registerGithubGetRepoReadmeInDirectoryTool } from "./tools/repositories/contents/github-get-repo-readme-in-directory.js";
import { registerGithubListCodeownersErrorsTool } from "./tools/repositories/github-list-codeowners-errors.js";
import { registerGithubListRepoContributorsTool } from "./tools/repositories/github-list-repo-contributors.js";
import { registerGithubListRepoActivitiesTool } from "./tools/repositories/github-list-repo-activities.js";
import { registerGithubListAuthenticatedUserReposTool } from "./tools/repositories/github-list-authenticated-user-repos.js";
import { registerGithubDeleteOrgTool } from "./tools/organizations/github-delete-org.js";
import { registerGithubGetOrgRouteStatsByActorTool } from "./tools/organizations/api-insights/github-get-org-route-stats-by-actor.js";
import { registerGithubGetOrgSubjectStatsTool } from "./tools/organizations/api-insights/github-get-org-subject-stats.js";
import { registerGithubGetOrgSummaryStatsTool } from "./tools/organizations/api-insights/github-get-org-summary-stats.js";
import { registerGithubGetOrgSummaryStatsByActorTool } from "./tools/organizations/api-insights/github-get-org-summary-stats-by-actor.js";
import { registerGithubGetOrgSummaryStatsByUserTool } from "./tools/organizations/api-insights/github-get-org-summary-stats-by-user.js";
import { registerGithubGetOrgTimeStatsTool } from "./tools/organizations/api-insights/github-get-org-time-stats.js";
import { registerGithubGetOrgTimeStatsByActorTool } from "./tools/organizations/api-insights/github-get-org-time-stats-by-actor.js";
import { registerGithubGetOrgTimeStatsByUserTool } from "./tools/organizations/api-insights/github-get-org-time-stats-by-user.js";
import { registerGithubGetOrgUserStatsTool } from "./tools/organizations/api-insights/github-get-org-user-stats.js";
import { registerGithubCreateUpdateOrgCustomPropertiesTool } from "./tools/organizations/custom-properties/github-create-update-org-custom-properties.js";
import { registerGithubCreateUpdateOrgCustomPropertyTool } from "./tools/organizations/custom-properties/github-create-update-org-custom-property.js";
import { registerGithubCreateUpdateOrgCustomPropertyValuesTool } from "./tools/organizations/custom-properties/github-create-update-org-custom-property-values.js";
import { registerGithubDeleteOrgCustomPropertyTool } from "./tools/organizations/custom-properties/github-delete-org-custom-property.js";
import { registerGithubGetOrgCustomPropertyTool } from "./tools/organizations/custom-properties/github-get-org-custom-property.js";
import { registerGithubListOrgCustomPropertyValuesTool } from "./tools/organizations/custom-properties/github-list-org-custom-property-values.js";
import { registerGithubGetOrgCustomPropertiesTool } from "./tools/organizations/custom-properties/github-get-org-custom-properties.js";
import { registerGithubCreateOrgIssueFieldTool } from "./tools/organizations/issue-fields/github-create-org-issue-field.js";
import { registerGithubDeleteOrgIssueFieldTool } from "./tools/organizations/issue-fields/github-delete-org-issue-field.js";
import { registerGithubListOrgIssueFieldsTool } from "./tools/organizations/issue-fields/github-list-org-issue-fields.js";
import { registerGithubUpdateOrgIssueFieldTool } from "./tools/organizations/issue-fields/github-update-org-issue-field.js";
import { registerGithubCreateOrgIssueTypeTool } from "./tools/organizations/issue-types/github-create-org-issue-type.js";
import { registerGithubDeleteOrgIssueTypeTool } from "./tools/organizations/issue-types/github-delete-org-issue-type.js";
import { registerGithubListOrgIssueTypesTool } from "./tools/organizations/issue-types/github-list-org-issue-types.js";
import { registerGithubUpdateOrgIssueTypeTool } from "./tools/organizations/issue-types/github-update-org-issue-type.js";
import { registerGithubGetOrgTool } from "./tools/organizations/github-get-org.js";
import { registerGithubGetOrgImmutableReleasesSettingsTool } from "./tools/organizations/github-get-org-immutable-releases-settings.js";
import { registerGithubDisableImmutableReleasesForOrgRepoTool } from "./tools/organizations/github-disable-immutable-releases-for-org-repo.js";
import { registerGithubEnableImmutableReleasesForOrgRepoTool } from "./tools/organizations/github-enable-immutable-releases-for-org-repo.js";
import { registerGithubCreateOrgArtifactDeploymentRecordTool } from "./tools/organizations/artifact-metadata/github-create-org-artifact-deployment-record.js";
import { registerGithubCreateOrgMetadataStorageRecordTool } from "./tools/organizations/artifact-metadata/github-create-org-metadata-storage-record.js";
import { registerGithubListOrgArtifactDeploymentRecordsTool } from "./tools/organizations/artifact-metadata/github-list-org-artifact-deployment-records.js";
import { registerGithubListOrgMetadataStorageRecordsTool } from "./tools/organizations/artifact-metadata/github-list-org-metadata-storage-records.js";
import { registerGithubDeleteOrgAttestationByIdTool } from "./tools/organizations/artifact-attestations/github-delete-org-attestation-by-id.js";
import { registerGithubDeleteOrgAttestationBySubjectDigestTool } from "./tools/organizations/artifact-attestations/github-delete-org-attestation-by-subject-digest.js";
import { registerGithubDeleteOrgAttestationsBulkTool } from "./tools/organizations/artifact-attestations/github-delete-org-attestations-bulk.js";
import { registerGithubListOrgAttestationReposTool } from "./tools/organizations/artifact-attestations/github-list-org-attestation-repos.js";
import { registerGithubListOrgAttestationsTool } from "./tools/organizations/artifact-attestations/github-list-org-attestations.js";
import { registerGithubListOrgAttestationsBulkSubjectDigestsTool } from "./tools/organizations/artifact-attestations/github-list-org-attestations-bulk-subject-digests.js";
import { registerGithubBlockOrgUserTool } from "./tools/organizations/blocking-users/github-block-org-user.js";
import { registerGithubCheckOrgBlockedUserTool } from "./tools/organizations/blocking-users/github-check-org-blocked-user.js";
import { registerGithubListOrgBlockedUsersTool } from "./tools/organizations/blocking-users/github-list-org-blocked-users.js";
import { registerGithubUnblockOrgUserTool } from "./tools/organizations/blocking-users/github-unblock-org-user.js";
import { registerGithubCancelOrgInvitationTool } from "./tools/organizations/members/github-cancel-org-invitation.js";
import { registerGithubCreateOrgInvitationTool } from "./tools/organizations/members/github-create-org-invitation.js";
import { registerGithubListOrgFailedInvitationsTool } from "./tools/organizations/members/github-list-org-failed-invitations.js";
import { registerGithubListOrgInvitationTeamsTool } from "./tools/organizations/members/github-list-org-invitation-teams.js";
import { registerGithubListOrgMembersTool } from "./tools/organizations/members/github-list-org-members.js";
import { registerGithubListOrgPendingInvitationsTool } from "./tools/organizations/members/github-list-org-pending-invitations.js";
import { registerGithubSetOrgClusterDeploymentRecordsTool } from "./tools/organizations/artifact-metadata/github-set-org-cluster-deployment-records.js";
import { registerGithubEnableOrDisableOrgSecurityFeatureTool } from "./tools/organizations/github-enable-or-disable-org-security-feature.js";
import { registerGithubListImmutableReleasesForOrgReposTool } from "./tools/organizations/github-list-immutable-releases-for-org-repos.js";
import { registerGithubListOrgAppInstallationsTool } from "./tools/organizations/github-list-org-app-installations.js";
import { registerGithubListOrganizationsTool } from "./tools/organizations/github-list-organizations.js";
import { registerGithubListOrgsForAuthenticatedUserTool } from "./tools/organizations/github-list-orgs-for-authenticated-user.js";
import { registerGithubListOrgsForUserTool } from "./tools/organizations/github-list-orgs-for-user.js";
import { registerGithubSetImmutableReleasesForOrgReposTool } from "./tools/organizations/github-set-immutable-releases-for-org-repos.js";
import { registerGithubSetOrgImmutableReleasesSettingsTool } from "./tools/organizations/github-set-org-immutable-releases-settings.js";
import { registerGithubUpdateOrgTool } from "./tools/organizations/github-update-org.js";
import { registerGithubListOrgReposTool } from "./tools/repositories/github-list-org-repos.js";
import { registerGithubListPublicReposTool } from "./tools/repositories/github-list-public-repos.js";
import { registerGithubCreateRepoForkTool } from "./tools/repositories/forks/github-create-repo-fork.js";
import { registerGithubListRepoForksTool } from "./tools/repositories/forks/github-list-repo-forks.js";
import { registerGithubCreateRepoRulesetTool } from "./tools/repositories/rules/github-create-repo-ruleset.js";
import { registerGithubDeleteRepoRulesetTool } from "./tools/repositories/rules/github-delete-repo-ruleset.js";
import { registerGithubGetRepoBranchRulesTool } from "./tools/repositories/rules/github-get-repo-branch-rules.js";
import { registerGithubGetRepoRulesetTool } from "./tools/repositories/rules/github-get-repo-ruleset.js";
import { registerGithubGetRepoRulesetHistoryTool } from "./tools/repositories/rules/github-get-repo-ruleset-history.js";
import { registerGithubGetRepoRulesetVersionTool } from "./tools/repositories/rules/github-get-repo-ruleset-version.js";
import { registerGithubListRepoRulesetsTool } from "./tools/repositories/rules/github-list-repo-rulesets.js";
import { registerGithubUpdateRepoRulesetTool } from "./tools/repositories/rules/github-update-repo-ruleset.js";
import { registerGithubGetRepoRuleSuiteTool } from "./tools/repositories/rule-suites/github-get-repo-rule-suite.js";
import { registerGithubListRepoRuleSuitesTool } from "./tools/repositories/rule-suites/github-list-repo-rule-suites.js";
import { registerGithubListRepoLanguagesTool } from "./tools/repositories/github-list-repo-languages.js";
import { registerGithubListRepoTagsTool } from "./tools/repositories/github-list-repo-tags.js";
import { registerGithubListRepoTeamsTool } from "./tools/repositories/github-list-repo-teams.js";
import { registerGithubListRepoTopicsTool } from "./tools/repositories/github-list-repo-topics.js";
import { registerGithubListUserReposTool } from "./tools/repositories/github-list-user-repos.js";
import { registerGithubCreateRepoWebhookTool } from "./tools/repositories/webhooks/github-create-repo-webhook.js";
import { registerGithubDeleteRepoWebhookTool } from "./tools/repositories/webhooks/github-delete-repo-webhook.js";
import { registerGithubGetRepoWebhookConfigTool } from "./tools/repositories/webhooks/github-get-repo-webhook-config.js";
import { registerGithubGetRepoWebhookDeliveryTool } from "./tools/repositories/webhooks/github-get-repo-webhook-delivery.js";
import { registerGithubGetRepoWebhookTool } from "./tools/repositories/webhooks/github-get-repo-webhook.js";
import { registerGithubListRepoWebhookDeliveriesTool } from "./tools/repositories/webhooks/github-list-repo-webhook-deliveries.js";
import { registerGithubListRepoWebhooksTool } from "./tools/repositories/webhooks/github-list-repo-webhooks.js";
import { registerGithubPingRepoWebhookTool } from "./tools/repositories/webhooks/github-ping-repo-webhook.js";
import { registerGithubTestPushRepoWebhookTool } from "./tools/repositories/webhooks/github-test-push-repo-webhook.js";
import { registerGithubRedeliverRepoWebhookDeliveryTool } from "./tools/repositories/webhooks/github-redeliver-repo-webhook-delivery.js";
import { registerGithubUpdateRepoWebhookConfigTool } from "./tools/repositories/webhooks/github-update-repo-webhook-config.js";
import { registerGithubUpdateRepoWebhookTool } from "./tools/repositories/webhooks/github-update-repo-webhook.js";
import { registerGithubReplaceRepoTopicsTool } from "./tools/repositories/github-replace-repo-topics.js";
import { registerGithubTransferRepoTool } from "./tools/repositories/github-transfer-repo.js";
import { registerGithubUpdateRepoTool } from "./tools/repositories/github-update-repo.js";

const token = getRequiredEnv("GITHUB_TOKEN");
const octokit = new Octokit({
    auth: token,
    headers: { "X-GitHub-Api-Version": "2026-03-10" }
});
const server = new McpServer({ name: "github-mcp", version: "1.0.0" });

// Register all MCP tools here; each tool implementation lives in its own file.
registerGithubCreatePersonalRepoTool(server, octokit);
registerGithubCreateOrgRepoTool(server, octokit);
registerGithubListOrganizationsTool(server, octokit);
registerGithubListOrgsForAuthenticatedUserTool(server, octokit);
registerGithubListOrgsForUserTool(server, octokit);
registerGithubListOrgAppInstallationsTool(server, octokit);
registerGithubGetOrgTool(server, octokit);
registerGithubListOrgIssueFieldsTool(server, octokit);
registerGithubCreateOrgIssueFieldTool(server, octokit);
registerGithubUpdateOrgIssueFieldTool(server, octokit);
registerGithubDeleteOrgIssueFieldTool(server, octokit);
registerGithubListOrgIssueTypesTool(server, octokit);
registerGithubCreateOrgIssueTypeTool(server, octokit);
registerGithubUpdateOrgIssueTypeTool(server, octokit);
registerGithubDeleteOrgIssueTypeTool(server, octokit);
registerGithubGetOrgCustomPropertiesTool(server, octokit);
registerGithubGetOrgCustomPropertyTool(server, octokit);
registerGithubCreateUpdateOrgCustomPropertiesTool(server, octokit);
registerGithubCreateUpdateOrgCustomPropertyTool(server, octokit);
registerGithubDeleteOrgCustomPropertyTool(server, octokit);
registerGithubListOrgCustomPropertyValuesTool(server, octokit);
registerGithubCreateUpdateOrgCustomPropertyValuesTool(server, octokit);
registerGithubGetOrgRouteStatsByActorTool(server, octokit);
registerGithubGetOrgSubjectStatsTool(server, octokit);
registerGithubGetOrgSummaryStatsTool(server, octokit);
registerGithubGetOrgSummaryStatsByActorTool(server, octokit);
registerGithubGetOrgSummaryStatsByUserTool(server, octokit);
registerGithubGetOrgTimeStatsTool(server, octokit);
registerGithubGetOrgTimeStatsByActorTool(server, octokit);
registerGithubGetOrgTimeStatsByUserTool(server, octokit);
registerGithubGetOrgUserStatsTool(server, octokit);
registerGithubGetOrgImmutableReleasesSettingsTool(server, octokit);
registerGithubSetOrgImmutableReleasesSettingsTool(server, octokit);
registerGithubListImmutableReleasesForOrgReposTool(server, octokit);
registerGithubEnableImmutableReleasesForOrgRepoTool(server, octokit);
registerGithubEnableOrDisableOrgSecurityFeatureTool(server, octokit);
registerGithubCreateOrgArtifactDeploymentRecordTool(server, octokit);
registerGithubCreateOrgMetadataStorageRecordTool(server, octokit);
registerGithubListOrgArtifactDeploymentRecordsTool(server, octokit);
registerGithubListOrgMetadataStorageRecordsTool(server, octokit);
registerGithubListOrgAttestationReposTool(server, octokit);
registerGithubListOrgAttestationsTool(server, octokit);
registerGithubListOrgAttestationsBulkSubjectDigestsTool(server, octokit);
registerGithubListOrgBlockedUsersTool(server, octokit);
registerGithubListOrgFailedInvitationsTool(server, octokit);
registerGithubListOrgPendingInvitationsTool(server, octokit);
registerGithubListOrgInvitationTeamsTool(server, octokit);
registerGithubCreateOrgInvitationTool(server, octokit);
registerGithubCancelOrgInvitationTool(server, octokit);
registerGithubListOrgMembersTool(server, octokit);
registerGithubCheckOrgBlockedUserTool(server, octokit);
registerGithubBlockOrgUserTool(server, octokit);
registerGithubUnblockOrgUserTool(server, octokit);
registerGithubDeleteOrgAttestationByIdTool(server, octokit);
registerGithubDeleteOrgAttestationBySubjectDigestTool(server, octokit);
registerGithubDeleteOrgAttestationsBulkTool(server, octokit);
registerGithubSetOrgClusterDeploymentRecordsTool(server, octokit);
registerGithubDisableImmutableReleasesForOrgRepoTool(server, octokit);
registerGithubSetImmutableReleasesForOrgReposTool(server, octokit);
registerGithubUpdateOrgTool(server, octokit);
registerGithubDeleteOrgTool(server, octokit);
registerGithubListOrgReposTool(server, octokit);
registerGithubCreateRepoFromTemplateTool(server, octokit);
registerGithubDeleteRepoTool(server, octokit);
registerGithubCheckDependabotSecurityUpdatesTool(server, octokit);
registerGithubCheckPrivateVulnerabilityReportingTool(server, octokit);
registerGithubCheckImmutableReleasesTool(server, octokit);
registerGithubEnableImmutableReleasesTool(server, octokit);
registerGithubDisableImmutableReleasesTool(server, octokit);
registerGithubCheckVulnerabilityAlertsTool(server, octokit);
registerGithubEnableVulnerabilityAlertsTool(server, octokit);
registerGithubDisableVulnerabilityAlertsTool(server, octokit);
registerGithubEnablePrivateVulnerabilityReportingTool(server, octokit);
registerGithubDisablePrivateVulnerabilityReportingTool(server, octokit);
registerGithubEnableDependabotSecurityUpdatesTool(server, octokit);
registerGithubDisableDependabotSecurityUpdatesTool(server, octokit);
registerGithubGetRepoTool(server, octokit);
registerGithubGetRepoContentTool(server, octokit);
registerGithubGetRepoReadmeTool(server, octokit);
registerGithubGetRepoReadmeInDirectoryTool(server, octokit);
registerGithubCreateUpdateFileContentsTool(server, octokit);
registerGithubDeleteFileTool(server, octokit);
registerGithubDownloadRepoArchiveTarTool(server, octokit);
registerGithubDownloadRepoArchiveZipTool(server, octokit);
registerGithubListRepoAutolinksTool(server, octokit);
registerGithubCreateRepoAutolinkTool(server, octokit);
registerGithubGetRepoAutolinkTool(server, octokit);
registerGithubDeleteRepoAutolinkTool(server, octokit);
registerGithubGetRepoCustomPropertyValuesTool(server, octokit);
registerGithubCreateUpdateRepoCustomPropertyValuesTool(server, octokit);
registerGithubListCodeownersErrorsTool(server, octokit);
registerGithubListRepoContributorsTool(server, octokit);
registerGithubListRepoActivitiesTool(server, octokit);
registerGithubListAuthenticatedUserReposTool(server, octokit);
registerGithubListPublicReposTool(server, octokit);
registerGithubListRepoLanguagesTool(server, octokit);
registerGithubListRepoForksTool(server, octokit);
registerGithubListRepoRuleSuitesTool(server, octokit);
registerGithubGetRepoRuleSuiteTool(server, octokit);
registerGithubGetRepoBranchRulesTool(server, octokit);
registerGithubListRepoRulesetsTool(server, octokit);
registerGithubGetRepoRulesetTool(server, octokit);
registerGithubGetRepoRulesetHistoryTool(server, octokit);
registerGithubGetRepoRulesetVersionTool(server, octokit);
registerGithubCreateRepoRulesetTool(server, octokit);
registerGithubUpdateRepoRulesetTool(server, octokit);
registerGithubDeleteRepoRulesetTool(server, octokit);
registerGithubCreateRepoForkTool(server, octokit);
registerGithubListRepoTagsTool(server, octokit);
registerGithubListRepoTeamsTool(server, octokit);
registerGithubListRepoTopicsTool(server, octokit);
registerGithubListUserReposTool(server, octokit);
registerGithubReplaceRepoTopicsTool(server, octokit);
registerGithubTransferRepoTool(server, octokit);
registerGithubUpdateRepoTool(server, octokit);
registerGithubCreateRepoDispatchTool(server, octokit);
registerGithubCreateRepoAttestationTool(server, octokit);
registerGithubListRepoAttestationsTool(server, octokit);
registerGithubListRepoWebhooksTool(server, octokit);
registerGithubListRepoWebhookDeliveriesTool(server, octokit);
registerGithubGetRepoWebhookDeliveryTool(server, octokit);
registerGithubRedeliverRepoWebhookDeliveryTool(server, octokit);
registerGithubPingRepoWebhookTool(server, octokit);
registerGithubTestPushRepoWebhookTool(server, octokit);
registerGithubGetRepoWebhookTool(server, octokit);
registerGithubGetRepoWebhookConfigTool(server, octokit);
registerGithubCreateRepoWebhookTool(server, octokit);
registerGithubUpdateRepoWebhookConfigTool(server, octokit);
registerGithubUpdateRepoWebhookTool(server, octokit);
registerGithubDeleteRepoWebhookTool(server, octokit);

async function main() {
    const transport = new StdioServerTransport();
    await server.connect(transport);
}

main().catch((error) => {
    // Keep startup failures explicit for MCP client logs.
    console.error("Failed to start github-mcp server:", error);
    process.exit(1);
});
